version: "3.9"
services:
  hivestat:
    build: .
    image: hivestat
    container_name: hivestat
    restart: unless-stopped
    environment:
      TZ: Pacific/Auckland
      INFLUX_IP: "192.168.1.254"
      INFLUX_PORT: "8086"
      INFLUX_USER: "admin"
      INFLUX_PASS: $INFLUX_PASS
      RIG_NAME: ""
    security_opt:
      - seccomp:unconfined
    volumes:
      - /run/hive/last_stat.json:/run/hive/last_stat.json:ro
