version: "3.9"
services:
  hivestat:
    build: .
    image: jonootto/hiveos-influx:latest
    container_name: hivestat
    restart: unless-stopped
    environment:
      TZ: Pacific/Auckland
      INFLUX_IP: $INFLUX_IP
      INFLUX_PORT: $INFLUX_PORT
      INFLUX_USER: $INFLUX_USER
      INFLUX_PASS: $INFLUX_PASS
      RIG_NAME: $RIG_NAME
    security_opt:
      - seccomp:unconfined
    volumes:
      - /run/hive/last_stat.json:/run/hive/last_stat.json:ro
